import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Toaster } from '@/components/ui/toaster'

import Header from '@/components/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Purpleroof',
    description: 'Generated by create next app'
}

export default function AuthLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <main className="flex h-auto min-h-screen flex-col">
                    <Header />
                    <div className='relative h-auto min-h-screen'>
                        <div className="absolute inset-0 -z-10 h-auto min-h-screen w-full bg-indigo-600 bg-opacity-25 bg-advertise bg-cover backdrop-opacity-10" />
                        <div
                            className="t-0 absolute top-0 -z-10 h-full w-full opacity-75"
                            style={{
                                background: 'linear-gradient(to bottom, #795695 30%, #795695 70%)'
                            }}
                        ></div>
                        <div className="absolute inset-0 bg-black opacity-50" />
                        {children}
                    </div>
                </main>
            </body>
            <Toaster />
        </html>
    )
}
