export const TypesOfProperties = [
  {
    label: 'Residential',
    value: 'Residential',
  },
  {
    label: 'Commercial',
    value: 'Commercial',
  },
]

export const CommercialTypes = [
  {
    label: 'Bulk Unit',
    value: 'Bulk Unit',
  },
  {
    label: 'Commercial Building',
    value: 'Commercial Building',
  },
  {
    label: 'Commercial Floor',
    value: 'Commercial Floor',
  },
  {
    label: 'Commercial Villa',
    value: 'Commercial Villa',
  },
  {
    label: 'Commercial Plot',
    value: 'Commercial Plot',
  },
  {
    label: 'Factory',
    value: 'Factory',
  },
  {
    label: 'Industrial Unit For Sale',
    value: 'Industrial Unit For Sale',
  },
  {
    label: 'Industrial Land',
    value: 'Industrial Land',
  },
  {
    label: 'Mixed Used Sand',
    value: 'Mixed Used Sand',
  },
  {
    label: 'Office For Sale',
    value: 'Office For Sale',
  },
  {
    label: 'Retail For Sale',
    value: 'Retail For Sale',
  },
  {
    label: 'Shop',
    value: 'Shop',
  },
  {
    label: 'Staff Accommodation for Sale',
    value: 'Staff Accommodation for Sale',
  },
  {
    label: 'Warehouse',
    value: 'Warehouse',
  },
  {
    label: 'Sell Commercial Land',
    value: 'Sell Commercial Land',
  },
  {
    label: 'Other',
    value: 'Other',
  },
]

export const ResidentalTypes = [
  {
    label: 'Apartment & Unit',
    value: 'Apartment & Unit',
  },
  {
    label: 'Villa',
    value: 'Villa',
  },
  {
    label: 'Acreage',
    value: 'Acreage',
  },
  {
    label: 'Block of Units',
    value: 'Block of Units',
  },
  {
    label: 'House',
    value: 'House',
  },
  {
    label: 'Townhouse',
    value: 'Townhouse',
  },
  {
    label: 'Land',
    value: 'Land',
  },
]

export const BedRooms = [
  {
    label: 'Studio',
    value: 'Studio',
  },
  {
    label: '1',
    value: '1',
  },
  {
    label: '2',
    value: '2',
  },
  {
    label: '3',
    value: '3',
  },
  {
    label: '4',
    value: '4',
  },
  {
    label: '5',
    value: '5',
  },
  {
    label: '6',
    value: '6',
  },
  {
    label: '7',
    value: '7',
  },
  {
    label: '8',
    value: '8',
  },
  {
    label: '9',
    value: '9',
  },
  {
    label: '10',
    value: '10',
  },
  {
    label: '11',
    value: '11',
  },
  {
    label: '12',
    value: '12',
  },
  {
    label: '13',
    value: '13',
  },
  {
    label: '14',
    value: '14',
  },
  {
    label: '15',
    value: '15',
  },
  {
    label: '16',
    value: '16',
  },
  {
    label: '17',
    value: '17',
  },
  {
    label: '18',
    value: '18',
  },
  {
    label: '19',
    value: '19',
  },
  {
    label: '20',
    value: '20',
  },
]

export const BathRooms = [
  {
    label: '1',
    value: '1',
  },
  {
    label: '2',
    value: '2',
  },
  {
    label: '3',
    value: '3',
  },
  {
    label: '4',
    value: '4',
  },
  {
    label: '5',
    value: '5',
  },
  {
    label: '6',
    value: '6',
  },
  {
    label: '7',
    value: '7',
  },
  {
    label: '8',
    value: '8',
  },
  {
    label: '9',
    value: '9',
  },
  {
    label: '10',
    value: '10',
  },
  {
    label: '11',
    value: '11',
  },
  {
    label: '12',
    value: '12',
  },
  {
    label: '13',
    value: '13',
  },
  {
    label: '14',
    value: '14',
  },
  {
    label: '15',
    value: '15',
  },
  {
    label: '16',
    value: '16',
  },
  {
    label: '17',
    value: '17',
  },
  {
    label: '18',
    value: '18',
  },
  {
    label: '19',
    value: '19',
  },
  {
    label: '20',
    value: '20',
  },
]

export const EmiratesWithLocations = [
  {
    emirate: 'Dubai',
    locations: [
      'Al Barsha',
      'Al Barsha 1',
      'Al Furjan',
      'Al Jaddaf',
      'Al Mankhool',
      'Al Nahda (Dubai)',
      'Al Nahda 2',
      'Al Quoz',
      'Al Qusais',
      'Al Wasl',
      'Arabian Ranches 3',
      'Arjan',
      'Azizi Riviera',
      'Bur Dubai',
      'Business Bay',
      'DAMAC Hills',
      'DAMAC Hills 2 (Akoya by DAMAC)',
      'Damac Lagoons',
      'Deira',
      'Downtown Dubai',
      'Dubai Creek Harbour',
      'Dubai Harbour',
      'Dubai Hills Estate',
      'Dubai Marina',
      'Dubai Silicon Oasis',
      'Dubai South',
      'Dubai Sports City',
      'Dubailand',
      'Elan',
      'Emaar Beachfront',
      'International City',
      'Jebel Ali',
      'Jumeirah',
      'Jumeirah Beach Residence (JBR)',
      'Jumeirah Lake Towers (JLT)',
      'Jumeirah Village Circle (JVC)',
      'Jumeirah Village Triangle (JVT)',
      'JVC District 10',
      'JVC District 11',
      'JVC District 12',
      'JVC District 13',
      'JVC District 14',
      'JVC District 15',
      'Meydan City',
      'Meydan One',
      'Mohammed Bin Rashid City',
      'Palm Jumeirah',
      'Sheikh Zayed Road',
      'Sobha Hartland',
      'Tilal Al Ghaf',
    ],
  },
  {
    emirate: 'Abu Dhabi',
    locations: [
      'Al Bateen',
      'Al Ghadeer',
      'Al Khalidiyah',
      'Al Matar',
      'Al Muneera',
      'Al Muroor',
      'Al Mushrif',
      'Al Nahyan',
      'Al Raha Beach',
      'Al Raha Gardens',
      'Al Reef',
      'Al Reef Downtown',
      'Al Reef Villas',
      'Al Reem Island',
      'Al Shamkha',
      'Baniyas',
      'Bloom Gardens',
      'City of Lights',
      'Corniche Area',
      'Corniche Road',
      'Electra Street',
      'Hamdan Street',
      'Khalifa City',
      'Madinat Al Riyadh',
      'Makers District',
      'Marina Square',
      'Masdar City',
      'Mayan',
      'Mohammed Bin Zayed City',
      'Mussafah',
      'Mussafah Community',
      'Mussafah Industrial Area',
      'Najmat Abu Dhabi',
      'Noya',
      'Pixel',
      'Reem Hills',
      'Saadiyat Beach',
      'Saadiyat Cultural District',
      'Saadiyat Island',
      'Shakhbout City',
      'Shams Abu Dhabi',
      'Shams Gate District',
      'Tamouh',
      'The Bridges',
      'The Gate Tower',
      'Tourist Club Area (TCA)',
      "Water's Edge",
      'Yas Acres',
      'Yas Island',
      'Zone 18',
    ],
  },
  {
    emirate: 'Ras Al Khaimah',
    locations: [
      'Al Dhait',
      'Al Dhait South',
      'Al Hamra Village',
      'Al Hamra Village Golf Apartments',
      'Al Mairid',
      'Al Mamourah',
      'Al Marjan Island',
      'Al Nakheel',
      'Al Qurm',
      'Al Qusaidat',
      'Al Refaa',
      'Al Seer',
      'Al Uraibi',
      'Aljazeera Al Hamra',
      'Bab Al Bahr Residences',
      'Bay Residences',
      'Bayviews',
      'Dafan Al Khor',
      'Dafan Al Nakheel',
      'Danah Bay',
      'ENI Mangrove',
      'Gateway II Residences',
      'Julphar Towers',
      'Kahraman Building',
      'Khuzam',
      'Marbella',
      'Marjan Island Resort & Spa',
      'Mina Al Arab',
      'Mudfak',
      'Oceano',
      'Pacific',
      'Pacific Bora Bora',
      'Pacific Samoa',
      'RAK Tower',
      'Royal Breeze 1',
      'Royal Breeze 2',
      'Royal Breeze 3',
      'Royal Breeze 4',
      'Royal Breeze 5',
      'Royal Breeze Apartment',
      'Seih Al Burairat',
      'Sidroh',
      'Suhaim',
      'The Cove Rotana',
      'The Lagoons',
      'Union Tower',
      'Yakout Building',
      'Yasmin Village',
      'Yasmin Village',
      'Yasmin Village Building 4',
    ],
  },
  {
    emirate: 'Sharjah',
    locations: [
      '5208 Muweilah Building',
      'Abu Shagara',
      'Ajmal Makan',
      'Al Ghuwair',
      'Al Khan',
      'Al Mahatah',
      'Al Majaz',
      'Al Majaz 1',
      'Al Majaz 2',
      'Al Majaz 3',
      'Al Mamsha',
      'Al Mamzar',
      'Al Nabba',
      'Al Nahda (Sharjah)',
      'Al Nahda Complex Towers',
      'Al Nahda Towers',
      'Al Nud',
      'Al Qasimia',
      'Al Rahmaniya',
      'Al Sajaa',
      'Al Sajaa Industrial',
      'Al Suyoh',
      'Al Taawun',
      'Al Tai',
      'Al Zahia',
      'Aljada',
      'Amber Tower',
      'Barashi',
      'Bu Tina',
      'Hayyan',
      'Hoshi',
      'Industrial Area',
      'Industrial Area 14',
      'Industrial Area 6',
      'Maryam Island',
      'Masaar',
      'Muwaileh',
      'Muwaileh 3 Building',
      'Muwaileh Building',
      'Muwailih Commercial',
      'Naseej District',
      'Nasma Residence',
      'Robinia',
      'Rove Home Aljada',
      'Sequoia',
      'Sharjah Garden City',
      'Sharjah Sustainable City',
      'Sharjah Waterfront City',
      'Shoumous Residential Complex',
      'Tilal City',
    ],
  },
  {
    emirate: 'Fujairah',
    locations: [
      'Address Fujairah Beach Resort',
      'Address Fujairah Beach Resort',
      'Address Residences Fujairah Resort',
      'Al Aqah',
      'Al Bidya',
      'Al Dana Island',
      'Al Fanar 2',
      'Al Fanar Towers',
      'Al Faseel Area',
      'Al Hayl',
      'Al Jaber Tower',
      'Al Taif Business Center',
      'Corniche Al Fujairah',
      'Dibba',
      'Fujairah Freezone',
      'Gurfah Area',
      'Ishwais',
      'Kalba',
      'Mattar Complex',
      'Mattar Residence',
      'Mattar Residence 2',
      'Mattar Residence 3',
      'Mattar Residence 4',
      'Mattar Residence 5',
      'Mattar Residence Mirbah',
      'Mattar Tower',
      'Merashid Area',
      'Mirbah',
      'Naseem Al Bahr Villas',
      'Platinum Time Residence',
      'Qidfa',
      'Sakamkam',
      'Saniaya',
      'Sharm',
      'The White Village',
      'Thoban',
      'Town Centre',
      'UNB Building Apartments',
    ],
  },
  {
    emirate: 'Ajman',
    locations: [
      'Ajman Corniche Residence',
      'Ajman Downtown',
      'Ajman Industrial',
      'Ajman Industrial 2',
      'Ajman One Towers',
      'Ajman Pearl Towers',
      'Al Alia',
      'Al Amerah',
      'Al Bustan',
      'Al Hamidiya 1',
      'Al Hamidiyah',
      'Al Helio',
      'Al Jurf',
      'Al Jurf 2',
      'Al Jurf Industrial 3',
      'Al Jurf Industrial Area',
      'Al Khor Towers',
      'Al Mowaihat',
      'Al Mowaihat 1',
      'Al Mowaihat 2',
      'Al Mowaihat 3',
      'Al Nakhil',
      'Al Nuaimiya',
      'Al Nuaimiya 1',
      'Al Nuaimiya 2',
      'Al Nuaimiya 3',
      'Al Nuaimiya Towers',
      'Al Rashidiya',
      'Al Rashidiya 1',
      'Al Rashidiya 2',
      'Al Rashidiya 3',
      'Al Rawda',
      'Al Rawda 1',
      'Al Rawda 2',
      'Al Rawda 3',
      'Al Rumaila',
      'Al Sawan',
      'Al Yasmeen',
      'Al Zahra',
      'Al Zahya',
      'Al Zorah',
      'City Tower',
      'Conqueror Tower',
      'Corniche Ajman',
      'Corniche Tower',
      'Emirates City',
      'Gulfa Towers',
      'Horizon Tower',
      'Paradise Lakes',
      'Sheikh Maktoum Bin Rashid Street',
    ],
  },
  {
    emirate: 'Umm al Quwain',
    locations: [
      'ADIB Building',
      'Al Aahad',
      'Al Abraq 1',
      'Al Butain',
      'Al Dar Al Baida',
      'Al Haditha',
      'Al Hawiyah',
      'Al Huboob 1',
      'Al Huboob 2',
      'Al Humrah',
      'Al Khor',
      'Al Maidan',
      'Al Maqtaa',
      'Al Ramlah',
      'Al Rass',
      'Al Raudah',
      'Al Riqqah',
      'Al Salam City',
      'Al Salamah',
      'Al Serra',
      'Al Shareiah',
      'Defence Camp',
      'Emirates Modern Industrial Area',
      'Falaj Al Mualla',
      'Falaj Al Sheikh',
      'Green Belt',
      'Industrial Area',
      'Kabir',
      'Khalifah City',
      'Khalifah City 1',
      'Khalifah City 2',
      'Mallah',
      'Masjid Al Mazroui',
      'Old Town Area',
      'Umm Al Quwain Marina',
      'Umm Dera',
    ],
  },
]

export const PropertyTypes = [
  {
    label: 'Free Hold',
    value: 'Free Hold',
  },
  {
    label: 'Lease Hold',
    value: 'Lease Hold',
  },
]

export const Statuses = [
  {
    label: 'Fully Furnished',
    value: 'Fully Furnished',
  },
  {
    label: 'Semi Furnished',
    value: 'Semi Furnished',
  },
  {
    label: 'Unfurnished',
    value: 'Unfurnished',
  },
]

export const Amenities = [
  {
    label: 'Property Type',
    value: 'Property Type',
  },
  {
    label: 'Completion status',
    value: 'Completion status',
  },
  {
    label: 'Balcony/ Terrace',
    value: 'Balcony/ Terrace',
  },
  {
    label: 'Double Glazed Windows',
    value: 'Double Glazed Windows',
  },
  {
    label: 'Centrally Air-Conditioned',
    value: 'Centrally Air-Conditioned',
  },
  {
    label: 'Central Heating',
    value: 'Central Heating',
  },
  {
    label: 'Electricity Backup',
    value: 'Electricity Backup',
  },
  {
    label: 'Storage Areas',
    value: 'Storage Areas',
  },
  {
    label: 'Study Room',
    value: 'Study Room',
  },
  {
    label: 'Maid Room',
    value: 'Maid Room',
  },
  {
    label: 'Driver Room',
    value: 'Driver Room',
  },
  {
    label: 'Laundry Room',
    value: 'Laundry Room',
  },
  {
    label: 'Private Swimming Pool',
    value: 'Private Swimming Pool',
  },
  {
    label: 'Number of Parking Spaces',
    value: 'Number of Parking Spaces',
  },
  {
    label: 'Recreation and Family',
    value: 'Recreation and Family',
  },
  {
    label: 'Barbeque Area',
    value: 'Barbeque Area',
  },
  {
    label: 'Day Care Center',
    value: 'Day Care Center',
  },
  {
    label: 'Kids Play Area',
    value: 'Kids Play Area',
  },
  {
    label: 'Lawn or Garden',
    value: 'Lawn or Garden',
  },
  {
    label: 'Cafeteria or Canteen',
    value: 'Cafeteria or Canteen',
  },
  {
    label: 'Laundry and Kitchen',
    value: 'Laundry and Kitchen',
  },
  {
    label: 'Laundry Facility',
    value: 'Laundry Facility',
  },
  {
    label: 'Shared Kitchen',
    value: 'Shared Kitchen',
  },
  {
    label: 'Lobby in Building',
    value: 'Lobby in Building',
  },
  {
    label: 'Elevators in Building',
    value: 'Elevators in Building',
  },
  {
    label: 'Service Elevators',
    value: 'Service Elevators',
  },
  {
    label: 'Prayer Room',
    value: 'Prayer Room',
  },
  {
    label: 'Reception/Waiting Room',
    value: 'Reception/Waiting Room',
  },
  {
    label: 'Health and Fitness',
    value: 'Health and Fitness',
  },
  {
    label: 'First Aid Medical Center',
    value: 'First Aid Medical Center',
  },
  {
    label: 'Jacuzzi',
    value: 'Jacuzzi',
  },
  {
    label: 'Sauna',
    value: 'Sauna',
  },
  {
    label: 'Steam Room',
    value: 'Steam Room',
  },
  {
    label: 'Swimming Pool',
    value: 'Swimming Pool',
  },
  {
    label: 'Facilities for Disabled',
    value: 'Facilities for Disabled',
  },
  {
    label: 'Security Staff',
    value: 'Security Staff',
  },
  {
    label: 'Business Center',
    value: 'Business Center',
  },
  {
    label: 'Pet Allowed',
    value: 'Pet Allowed',
  },
  {
    label: 'Cleaning and Maintenance',
    value: 'Cleaning and Maintenance',
  },
  {
    label: 'ATM Facility',
    value: 'ATM Facility',
  },
  {
    label: 'Nearby Schools',
    value: 'Nearby Schools',
  },
  {
    label: 'Nearby Hospitals',
    value: 'Nearby Hospitals',
  },
  {
    label: 'Nearby Mosque',
    value: 'Nearby Mosque',
  },
  {
    label: 'Nearby Shopping Malls',
    value: 'Nearby Shopping Malls',
  },
  {
    label: 'Distance from Airport',
    value: 'Distance from Airport',
  },
  {
    label: 'Nearby Metro Station',
    value: 'Nearby Metro Station',
  },
  {
    label: 'Other Nearby Places',
    value: 'Other Nearby Places',
  },
  {
    label: 'Other Main Features',
    value: 'Other Main Features',
  },
]
