export enum IncomeProfileEnum {
  SALARIED = 'SALARIED',
  SELF_EMPLOYED = 'SELF_EMPLOYED',
  RENTAL_INCOME = 'RENTAL_INCOME'
}

export enum ResidenceTypeEnum {
  UAE_NATIONAL = 'UAE_NATIONAL',
  UAE_RESIDENT = 'UAE_RESIDENT',
  NON_UAE_RESIDENT = 'NON_UAE_RESIDENT'
}

export enum MortgageStatusEnum {
  SUBMITTED = 'SUBMITTED',
  UNDER_DOCUMENTATION_STAGE = 'UNDER_DOCUMENTATION_STAGE',
  SUBMITTED_TO_BANK = 'SUBMITTED_TO_BANK',
  APPROVED = 'APPROVED',
  VALUATION_STAGE = 'VALUATION_STAGE',
  FINAL_OFFER_LETTER = 'FINAL_OFFER_LETTER',
  CASE_DISBURSED = 'CASE_DISBURSED',
  PROPERTY_TRANSFER = 'PROPERTY_TRANSFER',
  TRANSACTION_COMPLETED = 'TRANSACTION_COMPLETED',
  CASE_CLOSED = 'CASE_CLOSED',
  CASE_DECLINED = 'CASE_DECLINED'
}

export enum LoanTypeEnum {
  BUY_PROPERTY_FROM_SELLER = 'BUY_PROPERTY_FROM_SELLER',
  BUY_PROPERTY_FROM_DEVELOPER = 'BUY_PROPERTY_FROM_DEVELOPER',
  SHIFT_PROPERTY_LOAN = 'SHIFT_PROPERTY_LOAN',
  GET_CASH_AGAINST_EXISTING_PROPERTY = 'GET_CASH_AGAINST_EXISTING_PROPERTY'
}

export enum PropertyTypeEnum {
  RESIDENTIAL = 'RESIDENTIAL',
  COMMERCIAL = 'COMMERCIAL'
}

export enum CompletionStatusEnum {
  COMPLETED = 'COMPLETED',
  UNDER_CONSTRUCTION = 'UNDER_CONSTRUCTION'
}

export enum FinanceTypeEnum {
  ISLAMIC = 'ISLAMIC',
  CONVENTIONAL = 'CONVENTIONAL'
}

export enum EmirateEnum {
  DUBAI = 'DUBAI',
  ABU_DHABI = 'ABU_DHABI',
  RAS_AL_KHAIMAH = 'RAS_AL_KHAIMAH',
  SHARJAH = 'SHARJAH',
  FUJAIRAH = 'FUJAIRAH',
  AJMAN = 'AJMAN',
  UMM_AL_QUWAIN = 'UMM_AL_QUWAIN'
}

export enum EducationEnum {
  ELEMENTARY_SCHOOL = 'ELEMENTARY_SCHOOL',
  MIDDLE_SCHOOL = 'MIDDLE_SCHOOL',
  HIGH_SCHOOL = 'HIGH_SCHOOL',
  COLLEGE = 'COLLEGE',
  VOCATIONAL_SCHOOL = 'VOCATIONAL_SCHOOL',
  GRADUATE_SCHOOL = 'GRADUATE_SCHOOL',
  ONLINE_COURSES = 'ONLINE_COURSES',
  PROFESSIONAL_DEVELOPMENT = 'PROFESSIONAL_DEVELOPMENT',
  HOMESCHOOLING = 'HOMESCHOOLING',
  LIFELONG_LEARNING = 'LIFELONG_LEARNING',
  SPECIALIZED_TRAINING_PROGRAMS = 'SPECIALIZED_TRAINING_PROGRAMS',
  LANGUAGE_COURSES = 'LANGUAGE_COURSES',
  CERTIFICATE_PROGRAMS = 'CERTIFICATE_PROGRAMS',
  TRADE_SCHOOLS = 'TRADE_SCHOOLS'
}

export enum MaritalStatusEnum {
  SINGLE = 'SINGLE',
  MARRIED = 'MARRIED',
  WIDOWED = 'WIDOWED',
  SEPARATED = 'SEPARATED'
}

export enum RelationshipEnum {
  PARENT = 'PARENT',
  SIBLING = 'SIBLING',
  GRANDPARENT = 'GRANDPARENT',
  CHILD = 'CHILD',
  SPOUSE = 'SPOUSE',
  COUSIN = 'COUSIN',
  AUNT = 'AUNT',
  UNCLE = 'UNCLE',
  NIECE = 'NIECE',
  NEPHEW = 'NEPHEW',
  IN_LAW = 'IN_LAW',
  GUARDIAN = 'GUARDIAN',
  FOSTER_PARENT = 'FOSTER_PARENT',
  STEP_PARENT = 'STEP_PARENT',
  STEP_SIBLING = 'STEP_SIBLING'
}
